const questions = [
    {
        name: 'q01',
        text: '好奇心は旺盛なほうだと思う',
        nextYes: 'q02-01',
        nextNo: 'q02-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q02-01',
        text: '頭で考えるよりも行動する派である',
        nextYes: 'q03-01',
        nextNo: 'q03-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q02-02',
        text: '一つのことを長く継続できる',
        nextYes: 'q03-03',
        nextNo: 'q03-02',
    },
    {
        name: 'q03-01',
        text: '暇な時間やぼーっとしている時間はあまり好きではない',
        nextYes: 'q04-01',
        nextNo: 'q04-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q03-02',
        text: '友人関係は狭く、深く、が心地よい',
        nextYes: 'q04-03',
        nextNo: 'q04-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q03-03',
        text: '自分は個性的またはユニークだと思う',
        nextYes: 'q04-04',
        nextNo: 'q04-03',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q04-01',
        text: '組織やグループのリーダーになることが多い',
        nextYes: 'q05-01',
        nextNo: 'q05-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q04-02',
        text: '料理や雑貨など、買わずに自分で作ることが多い方だ',
        nextYes: 'q05-03',
        nextNo: 'q05-02',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q04-03',
        text: 'ボランティア活動など誰かの役に立てることが好きだ',
        nextYes: 'q05-03',
        nextNo: 'q05-04',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q04-04',
        text: '物事に熱中していると時間を忘れてしまうことがある',
        nextYes: 'q05-05',
        nextNo: 'q05-04',
        resultYes: '',
        resultNo: '',
    },
    {
        name: 'q05-01',
        text: '新しいものや知らないことは少々危険が伴っても試してみたくなる',
        nextYes: '',
        nextNo: 'q06-01',
        resultYes: '/service/check/type-a/',
        resultNo: '',
    },
    {
        name: 'q05-02',
        text: '特定の人と関わるよりも、大勢の友人と仲良くしたい',
        nextYes: '',
        nextNo: '',
        resultYes: '/service/check/type-a/',
        resultNo: '/service/check/type-b/',
    },
    {
        name: 'q05-03',
        text: '他人の手伝い等を優先して自分のことを後回しにしてしまうことがある',
        nextYes: '',
        nextNo: '',
        resultYes: '/service/check/type-b/',
        resultNo: '/service/check/type-c/',
    },
    {
        name: 'q05-04',
        text: '事前に計画をたて慎重にすすめていく方である',
        nextYes: '',
        nextNo: '',
        resultYes: '/service/check/type-c/',
        resultNo: '/service/check/type-d/',
    },
    {
        name: 'q05-05',
        text: '物事は一つ一つこだわって選ぶ方だ',
        nextYes: '',
        nextNo: 'q06-02',
        resultYes: '/service/check/type-d/',
        resultNo: '',
    },
    {
        name: 'q06-01',
        text: '特定の人と関わるよりも、大勢の友人と仲良くしたい',
        nextYes: '',
        nextNo: '',
        resultYes: '/service/check/type-a/',
        resultNo: '/service/check/type-b/',
    },
    {
        name: 'q06-02',
        text: '事前に計画をたて慎重にすすめていく方である',
        nextYes: '',
        nextNo: '',
        resultYes: '/service/check/type-c/',
        resultNo: '/service/check/type-d/',
    },
];

export default questions;
